version: '3'

services:

  ob:
    image: buzz42/overbooking
    ports:
      - 8080:8080
    environment:
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - LOGGING_LEVEL_ROOT
    links:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379